"""
ComfyUI-SD-CN-Animation
Port of SD-CN-Animation txt2vid and vid2vid pipelines to ComfyUI custom nodes.
Uses FloweR/RAFT optical flow + two-pass SD sampling for temporally coherent video generation.

Original: https://github.com/volotat/SD-CN-Animation
"""

from .nodes.nodes_flower import NODE_CLASS_MAPPINGS as FLOWER_NODES, NODE_DISPLAY_NAME_MAPPINGS as FLOWER_NAMES
from .nodes.nodes_txt2vid import NODE_CLASS_MAPPINGS as TXT2VID_NODES, NODE_DISPLAY_NAME_MAPPINGS as TXT2VID_NAMES
from .nodes.nodes_vid2vid import NODE_CLASS_MAPPINGS as VID2VID_NODES, NODE_DISPLAY_NAME_MAPPINGS as VID2VID_NAMES
from .nodes.nodes_utils import NODE_CLASS_MAPPINGS as UTILS_NODES, NODE_DISPLAY_NAME_MAPPINGS as UTILS_NAMES
from .nodes.nodes_prompt_schedule import NODE_CLASS_MAPPINGS as SCHED_NODES, NODE_DISPLAY_NAME_MAPPINGS as SCHED_NAMES
from .nodes.nodes_motion_ctrl import NODE_CLASS_MAPPINGS as MOTION_NODES, NODE_DISPLAY_NAME_MAPPINGS as MOTION_NAMES

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(FLOWER_NODES)
NODE_CLASS_MAPPINGS.update(TXT2VID_NODES)
NODE_CLASS_MAPPINGS.update(VID2VID_NODES)
NODE_CLASS_MAPPINGS.update(UTILS_NODES)
NODE_CLASS_MAPPINGS.update(SCHED_NODES)
NODE_CLASS_MAPPINGS.update(MOTION_NODES)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(FLOWER_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(TXT2VID_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(VID2VID_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(UTILS_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(SCHED_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(MOTION_NAMES)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]

WEB_DIRECTORY = None
