"""
Motion control node for SD-CN-Animation.
Produces a MOTION_CTRL dict consumed by Txt2Vid to influence
FloweR's predicted flow, occlusion, and frame transforms.
"""


class SDCNMotionCtrl:
    """
    Control motion in the Txt2Vid pipeline.
    Wire into the motion_ctrl input — without it, Txt2Vid behaves as normal.
    """

    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "occlusion_multiplier": ("FLOAT", {
                    "default": 10.0, "min": 0.0, "max": 50.0, "step": 0.5,
                    "tooltip": "Amplifies occlusion mask. Higher = more of each frame gets regenerated by SD. Default 10.0 matches standard behavior."
                }),
                "flow_scale": ("FLOAT", {
                    "default": 1.0, "min": 0.0, "max": 3.0, "step": 0.05,
                    "tooltip": "Multiplier on predicted optical flow magnitude. <1 = slower motion, >1 = exaggerated motion."
                }),
                "pan_x": ("FLOAT", {
                    "default": 0.0, "min": -20.0, "max": 20.0, "step": 0.5,
                    "tooltip": "Horizontal drift in pixels/frame added to flow. Positive = pan right."
                }),
                "pan_y": ("FLOAT", {
                    "default": 0.0, "min": -20.0, "max": 20.0, "step": 0.5,
                    "tooltip": "Vertical drift in pixels/frame added to flow. Positive = pan down."
                }),
                "zoom": ("FLOAT", {
                    "default": 1.0, "min": 0.9, "max": 1.1, "step": 0.001,
                    "tooltip": "Per-frame scale factor. >1 = zoom in, <1 = zoom out. Subtle values like 1.005 work best."
                }),
                "rotate": ("FLOAT", {
                    "default": 0.0, "min": -5.0, "max": 5.0, "step": 0.1,
                    "tooltip": "Degrees/frame rotation applied to the prediction."
                }),
            }
        }

    RETURN_TYPES = ("MOTION_CTRL",)
    RETURN_NAMES = ("motion_ctrl",)
    FUNCTION = "create"
    CATEGORY = "SD-CN-Animation"
    DESCRIPTION = (
        "Controls motion in the Txt2Vid pipeline. Modifies FloweR's predicted "
        "optical flow and applies spatial transforms to influence animation direction and speed."
    )

    def create(self, occlusion_multiplier, flow_scale, pan_x, pan_y, zoom, rotate):
        return ({
            "occlusion_multiplier": occlusion_multiplier,
            "flow_scale": flow_scale,
            "pan_x": pan_x,
            "pan_y": pan_y,
            "zoom": zoom,
            "rotate": rotate,
        },)


NODE_CLASS_MAPPINGS = {
    "SDCNMotionCtrl": SDCNMotionCtrl,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "SDCNMotionCtrl": "SD-CN Motion Control",
}
